version=1.0.0
group=dev.lukamadness
java_version=21

minecraft_version=1.21.1
mod_name=Madness Core
mod_author=LukaMadness
mod_id=madnesscore
license=unlicense
credits=
description=
minecraft_version_range=[1.21.1,)

# Parchment
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Fabric
fabric_version=0.116.15+1.21.1
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=21.1.248
neoforge_loader_version_range=[1,)
neo_form_version=1.21.1-20240808.144430

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false