plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
        }
    }
}

neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        data {
            data()
            programArgument '--mod'
            programArgument mod_id
            programArgument '--all'
            programArgument '--output'
            programArgument file('src/generated/resources').absolutePath
            programArgument '--existing'
            programArgument file('src/main/resources').absolutePath
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}